// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xData.Data;

#nullable disable

namespace xData.Migrations
{
    [DbContext(typeof(paymentContext))]
    [Migration("20230401130656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("xDomain._91128.AccessLevel", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uid"));

                    b.Property<int?>("Usersuid")
                        .HasColumnType("int");

                    b.Property<int>("accessTypeNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_dt")
                        .HasColumnType("datetime2");

                    b.Property<int>("formTypeNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_dt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userRef")
                        .HasColumnType("int");

                    b.HasKey("uid");

                    b.HasIndex("Usersuid");

                    b.ToTable("AccessLevel");
                });

            modelBuilder.Entity("xDomain._91128.User", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uid"));

                    b.Property<string>("addressTx")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactTx")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("created_dt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("emailTx")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("employeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("firstNm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("isActive_yn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("lastNm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("middleNm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("passwordTx")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updated_dt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("usernameTx")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("uid");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            uid = 1,
                            addressTx = "address",
                            contactTx = "contact",
                            created_dt = new DateTime(2023, 4, 1, 21, 6, 56, 809, DateTimeKind.Local).AddTicks(2194),
                            emailTx = "dummy.erick@gmail.com",
                            employeeNo = "A2023",
                            firstNm = "Admin",
                            isActive_yn = true,
                            lastNm = "Admin",
                            middleNm = "Admin",
                            passwordTx = "p@ssw0rd",
                            updated_dt = new DateTime(2023, 4, 1, 21, 6, 56, 809, DateTimeKind.Local).AddTicks(2203),
                            usernameTx = "Admin"
                        });
                });

            modelBuilder.Entity("xDomain._91128.AccessLevel", b =>
                {
                    b.HasOne("xDomain._91128.User", "Users")
                        .WithMany("AccessLevels")
                        .HasForeignKey("Usersuid");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("xDomain._91128.User", b =>
                {
                    b.Navigation("AccessLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
